export const IMPORT_MATERIAL_CLEAR_STATE = 'material/clearState';
export const IMPORT_MATERIAL_GENERATE_NOT_IMPORTED_MATERIALS = 'material/generateNotImportedMaterials';
export const IMPORT_MATERIAL_GENERATE_IMPORTED_MATERIALS = 'material/generateImportedMaterials';
export const IMPORT_PRODUCT_GENERATE_IMPORTED_PRODUCTS = 'product/generateImportedProducts';
export const IMPORT_PRODUCT_GENERATE_NOT_IMPORTED_PRODUCTS = 'product/generateNotImportedProducts';
export const IMPORT_CREATE_PRODUCT_PRICE = 'product/createProductPrice';

export const SYSTEM_TASKS_DEFAULT_CHECKBOX = 'SYSTEMTASKS_DEFAULT_CHECKBOX';
export const SYSTEM_TASK_GENERATE_TASKS = 'SYSTEM_TASKS_GENERATE_TASKS';
export const FROM_SUPPLIERS_GENERATE_SUPPLIERS = 'FROM_SUPPLIERS';
export const FROM_SIZES_GENERATE_SIZES = 'FROM_SIZES';

export const IMPORT_PRODUCTS_GENERATE = 'IMPORT_PRODUCTS_GENERATE';

export const FROM_COLLECTIONS_GENERATE_COLLECTIONS = 'FROM_COLLECTIONS';
export const FROM_COLORS_GENERATE_COLORS = 'FROM_COLORS';
export const FROM_GRIDS_GENERATE_GRIDS = 'FROM_GRIDS';
export const FROM_LAUNCHIES_GENERATE_LAUNCHIES = 'FROM_LAUNCHIES';
export const FROM_MATERIAL_CLASSIFICATIONS_GENERATE_MATERIAL_CLASSIFICATIONS = 'FROM_MATERIAL_CLASSIFICATIONS';
export const FROM_PRINCINGS_GENERATE_PRINCINGS = 'FROM_PRINCINGS';
export const FROM_PRODUCT_CLASSIFICATIONS_GENERATE_PRODUCT_CLASSIFICATIONS = 'FROM_PRODUCT_CLASSIFICATIONS';

export const FROM_CATEGORIES_GENERATE_CATEGORIES = 'FROM_CATEGORIES';

export const REPORT_CHANGE_STATUS_PRODUCTS_GENERATE = 'REPORT_CHANGE_STATUS_PRODUCTS';

export const DEFAULT_CHECKBOX = 'DEFAULT_CHECKBOX';
export const STORE_FROM = 'from';
