export const SYSTEM_TASKS = 'SYSTEM_TASKS';
export const SYSTEM_TASKS_COLUMNS = 'SYSTEM_TASKS_COLUMNS';

export const IMPORT_PRODUCTS_IMPORTABLE = 'IMPORT_PRODUCTS_IMPORTABLE';
export const IMPORT_PRODUCTS_COLUMNS_IMPORTABLE = 'IMPORT_PRODUCTS_COLUMNS_IMPORTABLE';
export const IMPORT_PRODUCTS_NOT_IMPORTABLE = 'IMPORT_PRODUCTS_NOT_IMPORTABLE';
export const IMPORT_PRODUCTS_COLUMNS_NOT_IMPORTABLE = 'IMPORT_PRODUCTS_COLUMNS_NOT_IMPORTABLE';

export const IMPORT_MATERIALS_IMPORTABLE = 'IMPORT_MATERIALS_IMPORTABLE';
export const IMPORT_MATERIALS_COLUMNS_IMPORTABLE = 'IMPORT_MATERIALS_COLUMNS_IMPORTABLE';
export const IMPORT_MATERIALS_NOT_IMPORTABLE = 'IMPORT_MATERIALS_NOT_IMPORTABLE';
export const IMPORT_MATERIALS_COLUMNS_NOT_IMPORTABLE = 'IMPORT_MATERIALS_COLUMNS_NOT_IMPORTABLE';

export const FROM_SUPPLIERS = 'FROM_SUPPLIERS';
export const FROM_SUPPLIERS_COLUMNS = 'FROM_SUPPLIERS_COLUMNS';

export const FROM_SIZES = 'FROM_SIZES';
export const FROM_SIZES_COLUMNS = 'FROM_SIZES_COLUMNS';

export const FROM_CATEGORIES = 'FROM_CATEGORIES';
export const FROM_CATEGORIES_COLUMNS = 'FROM_CATEGORIES_COLUMNS';

export const FROM_COLLECTIONS = 'FROM_COLLECTIONS';
export const FROM_COLLECTIONS_COLUMNS = 'FROM_COLLECTIONS_COLUMNS';

export const FROM_COLORS = 'FROM_COLORS';
export const FROM_COLORS_COLUMNS = 'FROM_COLORS_COLUMNS';

export const FROM_GRIDS = 'FROM_GRIDS';
export const FROM_GRIDS_COLUMNS = 'FROM_GRIDS_COLUMNS';

export const FROM_LAUNCHIES = 'FROM_LAUNCHIES';
export const FROM_LAUNCHIES_COLUMNS = 'FROM_LAUNCHIES_COLUMNS';

export const FROM_MATERIAL_CLASSIFICATIONS = 'FROM_MATERIAL_CLASSIFICATIONS';
export const FROM_MATERIAL_CLASSIFICATIONS_COLUMNS = 'FROM_MATERIAL_CLASSIFICATIONS_COLUMNS';

export const FROM_PRINCINGS = 'FROM_PRINCINGS';
export const FROM_PRINCINGS_COLUMNS = 'FROM_PRINCINGS_COLUMNS';

export const FROM_PRODUCT_CLASSIFICATIONS = 'FROM_PRODUCT_CLASSIFICATIONS';
export const FROM_PRODUCT_CLASSIFICATIONS_COLUMNS = 'FROM_PRODUCT_CLASSIFICATIONS_COLUMNS';

export const REPORT_CHANGE_STATUS_PRODUCTS = 'REPORT_CHANGE_STATUS_PODUCTS';
export const REPORT_CHANGE_STATUS_PRODUCTS_COLUMNS = 'REPORT_CHANGE_STATUS_PRODUCTS_COLUMNS';
