export const SYSTEM_TASKS = "SYSTEM_TASKS";
export const SYSTEM_TASKS_COLUMNS = "SYSTEM_TASKS_COLUMNS";
export const FROM_SUPPLIERS = "FROM_SUPPLIERS";
export const FROM_SUPPLIERS_COLUMNS = "FROM_SUPPLIERS_COLUMNS";
